### ISSUE TITLE
Labels with apostrophe(') do not work

### ISSUE THREAD

**Issue by johnsamuelwrites** [dpriskorn/ItemSubjector#18]
Labels with apostrophe(') currently do not work. I think that an escape character needs to be added, before sending the query string to WDQS.

Take for example: 

Alzheimer's disease (Q11081)

returns the following error

> Fetching items with labels that have one of the search strings by running a total of 11 queries on WDQS...INFO:backoff:Backing off execute_sparql_query(...) for 1.0s (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url

**Comment by dpriskorn** [comment]
Try the latest pre-release and see if it works https://github.com/dpriskorn/ItemSubjector/releases/tag/v0.2-alpha1 :)

**Comment by johnsamuelwrites** [comment]
@dpriskorn Thanks for this pre-release change, it's working.

**Comment by dpriskorn** [comment]
fixed by #25
